# Generated by Django 4.2 on 2023-10-19 08:34

from django.db import migrations, models
import django.db.models.deletion
import doge_indexer.models.model_utils


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DogeBlock",
            fields=[
                (
                    "block_hash",
                    doge_indexer.models.model_utils.HexString32ByteField(
                        db_column="blockHash", max_length=64, primary_key=True, serialize=False
                    ),
                ),
                ("block_number", models.PositiveIntegerField(db_column="blockNumber")),
                ("timestamp", models.PositiveBigIntegerField(db_column="timestamp")),
                (
                    "previous_block_hash",
                    doge_indexer.models.model_utils.HexString32ByteField(db_column="previousBlockHash", max_length=64),
                ),
                ("transactions", models.PositiveIntegerField(db_column="transactions")),
                ("confirmed", models.BooleanField(db_column="confirmed", default=False)),
            ],
        ),
        migrations.CreateModel(
            name="DogeTransaction",
            fields=[
                (
                    "transaction_id",
                    doge_indexer.models.model_utils.HexString32ByteField(
                        db_column="transactionId", max_length=64, primary_key=True, serialize=False
                    ),
                ),
                ("block_number", models.PositiveIntegerField(db_column="blockNumber")),
                ("timestamp", models.PositiveBigIntegerField(db_column="timestamp")),
                (
                    "payment_reference",
                    doge_indexer.models.model_utils.HexString32ByteField(db_column="paymentReference", max_length=64),
                ),
                ("is_native_payment", models.BooleanField(db_column="isNativePayment", default=False)),
                ("transaction_type", models.CharField(db_column="transactionType")),
            ],
        ),
        migrations.CreateModel(
            name="TipSyncState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "sync_state",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("sync", "Syncing"),
                            ("up_to_date", "Up to date"),
                            ("error", "Error"),
                        ],
                        db_column="syncState",
                        max_length=10,
                    ),
                ),
                ("latest_tip_height", models.PositiveIntegerField(db_column="latestTipHeight")),
                ("latest_indexed_height", models.PositiveIntegerField(db_column="latestIndexedHeight")),
                ("timestamp", models.PositiveIntegerField(db_column="timestamp")),
            ],
        ),
        migrations.CreateModel(
            name="TransactionOutput",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("n", models.PositiveIntegerField(db_column="n")),
                ("value", models.CharField(db_column="value")),
                ("script_key_asm", models.CharField(db_column="scriptKeyAsm")),
                ("script_key_hex", models.CharField(db_column="scriptKeyHex")),
                ("script_key_req_sigs", models.CharField(blank=True, db_column="scriptKeyReqSigs", null=True)),
                ("script_key_type", models.CharField(db_column="scriptKeyType")),
                ("script_key_address", models.CharField(db_column="scriptKeyAddress", max_length=64)),
                (
                    "transaction_link",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="doge_indexer.dogetransaction"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionInputCoinbase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("vin_n", models.PositiveIntegerField(db_column="vinN")),
                ("vin_coinbase", models.CharField(db_column="vinCoinbase")),
                ("vin_sequence", models.PositiveBigIntegerField(db_column="vinSequence")),
                (
                    "transaction_link",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="doge_indexer.dogetransaction"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionInput",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("n", models.PositiveIntegerField(db_column="n")),
                ("value", models.CharField(db_column="value")),
                ("script_key_asm", models.CharField(db_column="scriptKeyAsm")),
                ("script_key_hex", models.CharField(db_column="scriptKeyHex")),
                ("script_key_req_sigs", models.CharField(blank=True, db_column="scriptKeyReqSigs", null=True)),
                ("script_key_type", models.CharField(db_column="scriptKeyType")),
                ("script_key_address", models.CharField(db_column="scriptKeyAddress", max_length=64)),
                ("vin_n", models.PositiveIntegerField(db_column="vinN")),
                (
                    "vin_previous_txid",
                    doge_indexer.models.model_utils.HexString32ByteField(db_column="vinPreviousTxid", max_length=64),
                ),
                ("vin_vout_index", models.PositiveIntegerField(db_column="vinVoutIndex")),
                ("vin_sequence", models.PositiveBigIntegerField(db_column="vinSequence")),
                ("vin_script_sig_asm", models.CharField(db_column="vinScriptSigAsm")),
                ("vin_script_sig_hex", models.CharField(db_column="vinScriptSigHex")),
                (
                    "transaction_link",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="doge_indexer.dogetransaction"),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="dogetransaction",
            index=models.Index(fields=["block_number"], name="doge_indexe_blockNu_b81a27_idx"),
        ),
        migrations.AddIndex(
            model_name="dogetransaction",
            index=models.Index(fields=["timestamp"], name="doge_indexe_timesta_1f5a82_idx"),
        ),
        migrations.AddIndex(
            model_name="dogetransaction",
            index=models.Index(fields=["payment_reference"], name="doge_indexe_payment_efb702_idx"),
        ),
        migrations.AddIndex(
            model_name="dogetransaction",
            index=models.Index(fields=["transaction_type"], name="doge_indexe_transac_4bb3b0_idx"),
        ),
        migrations.AddIndex(
            model_name="dogeblock",
            index=models.Index(fields=["block_number"], name="doge_indexe_blockNu_9e64fe_idx"),
        ),
        migrations.AddIndex(
            model_name="dogeblock",
            index=models.Index(fields=["timestamp"], name="doge_indexe_timesta_752a6d_idx"),
        ),
        migrations.AddIndex(
            model_name="dogeblock",
            index=models.Index(fields=["previous_block_hash"], name="doge_indexe_previou_95cdf7_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="transactionoutput",
            unique_together={("transaction_link", "n")},
        ),
        migrations.AlterUniqueTogether(
            name="transactioninput",
            unique_together={("transaction_link", "vin_n")},
        ),
    ]
