# Generated by Django 4.2 on 2023-10-03 16:54

from django.db import migrations, models
import django.db.models.deletion
import doge_indexer.models.model_utils


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DogeBlock",
            fields=[
                (
                    "blockHash",
                    doge_indexer.models.model_utils.HexString32ByteField(
                        max_length=64, primary_key=True, serialize=False
                    ),
                ),
                ("blockNumber", models.PositiveIntegerField()),
                ("timestamp", models.PositiveBigIntegerField()),
                ("previousBlockHash", doge_indexer.models.model_utils.HexString32ByteField(max_length=64)),
                ("transactions", models.PositiveIntegerField()),
                ("confirmed", models.BooleanField(default=False)),
                ("numberOfConfirmations", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="DogeTransaction",
            fields=[
                (
                    "transactionId",
                    doge_indexer.models.model_utils.HexString32ByteField(
                        max_length=64, primary_key=True, serialize=False
                    ),
                ),
                ("blockNumber", models.PositiveIntegerField()),
                ("timestamp", models.PositiveBigIntegerField()),
                ("paymentReference", doge_indexer.models.model_utils.HexString32ByteField(max_length=64)),
                ("isNativePayment", models.BooleanField(default=False)),
                ("transactionType", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="TransactionOutput",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("n", models.PositiveIntegerField()),
                ("value", models.DecimalField(decimal_places=8, max_digits=22)),
                ("script_key_asm", models.CharField()),
                ("script_key_hex", models.CharField()),
                ("script_key_req_sigs", models.CharField(blank=True, null=True)),
                ("script_key_type", models.CharField()),
                ("script_key_address", models.CharField(max_length=64)),
                (
                    "transaction_link",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="doge_indexer.dogetransaction"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionInputCoinbase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("vin_n", models.PositiveIntegerField()),
                ("vin_coinbase", models.CharField()),
                ("vin_sequence", models.PositiveBigIntegerField()),
                (
                    "transaction_link",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="doge_indexer.dogetransaction"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionInput",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("n", models.PositiveIntegerField()),
                ("value", models.DecimalField(decimal_places=8, max_digits=22)),
                ("script_key_asm", models.CharField()),
                ("script_key_hex", models.CharField()),
                ("script_key_req_sigs", models.CharField(blank=True, null=True)),
                ("script_key_type", models.CharField()),
                ("script_key_address", models.CharField(max_length=64)),
                ("vin_n", models.PositiveIntegerField()),
                ("vin_previous_txid", doge_indexer.models.model_utils.HexString32ByteField(max_length=64)),
                ("vin_vout_index", models.PositiveIntegerField()),
                ("vin_sequence", models.PositiveBigIntegerField()),
                ("vin_script_sig_asm", models.CharField()),
                ("vin_script_sig_hex", models.CharField()),
                (
                    "transaction_link",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="doge_indexer.dogetransaction"),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="dogetransaction",
            index=models.Index(fields=["blockNumber"], name="doge_indexe_blockNu_b81a27_idx"),
        ),
        migrations.AddIndex(
            model_name="dogetransaction",
            index=models.Index(fields=["timestamp"], name="doge_indexe_timesta_1f5a82_idx"),
        ),
        migrations.AddIndex(
            model_name="dogetransaction",
            index=models.Index(fields=["paymentReference"], name="doge_indexe_payment_efb702_idx"),
        ),
        migrations.AddIndex(
            model_name="dogetransaction",
            index=models.Index(fields=["transactionType"], name="doge_indexe_transac_4bb3b0_idx"),
        ),
        migrations.AddIndex(
            model_name="dogeblock",
            index=models.Index(fields=["blockNumber"], name="doge_indexe_blockNu_9e64fe_idx"),
        ),
        migrations.AddIndex(
            model_name="dogeblock",
            index=models.Index(fields=["timestamp"], name="doge_indexe_timesta_752a6d_idx"),
        ),
        migrations.AddIndex(
            model_name="dogeblock",
            index=models.Index(fields=["previousBlockHash"], name="doge_indexe_previou_95cdf7_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="transactionoutput",
            unique_together={("transaction_link", "n")},
        ),
        migrations.AlterUniqueTogether(
            name="transactioninput",
            unique_together={("transaction_link", "vin_n")},
        ),
    ]
