# Generated by Django 4.2 on 2023-10-09 13:47

from django.db import migrations, models
import django.db.models.deletion
import doge_indexer.models.model_utils


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DogeBlock",
            fields=[
                (
                    "block_hash",
                    doge_indexer.models.model_utils.HexString32ByteField(
                        max_length=64, primary_key=True, serialize=False
                    ),
                ),
                ("block_number", models.PositiveIntegerField()),
                ("timestamp", models.PositiveBigIntegerField()),
                ("previous_block_hash", doge_indexer.models.model_utils.HexString32ByteField(max_length=64)),
                ("transactions", models.PositiveIntegerField()),
                ("confirmed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="DogeTransaction",
            fields=[
                (
                    "transaction_id",
                    doge_indexer.models.model_utils.HexString32ByteField(
                        max_length=64, primary_key=True, serialize=False
                    ),
                ),
                ("block_number", models.PositiveIntegerField()),
                ("timestamp", models.PositiveBigIntegerField()),
                ("payment_reference", doge_indexer.models.model_utils.HexString32ByteField(max_length=64)),
                ("is_native_payment", models.BooleanField(default=False)),
                ("transaction_type", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="TransactionOutput",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("n", models.PositiveIntegerField()),
                ("value", models.DecimalField(decimal_places=8, max_digits=22)),
                ("script_key_asm", models.CharField()),
                ("script_key_hex", models.CharField()),
                ("script_key_req_sigs", models.CharField(blank=True, null=True)),
                ("script_key_type", models.CharField()),
                ("script_key_address", models.CharField(max_length=64)),
                (
                    "transaction_link",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="doge_indexer.dogetransaction"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionInputCoinbase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("vin_n", models.PositiveIntegerField()),
                ("vin_coinbase", models.CharField()),
                ("vin_sequence", models.PositiveBigIntegerField()),
                (
                    "transaction_link",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="doge_indexer.dogetransaction"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionInput",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("n", models.PositiveIntegerField()),
                ("value", models.DecimalField(decimal_places=8, max_digits=22)),
                ("script_key_asm", models.CharField()),
                ("script_key_hex", models.CharField()),
                ("script_key_req_sigs", models.CharField(blank=True, null=True)),
                ("script_key_type", models.CharField()),
                ("script_key_address", models.CharField(max_length=64)),
                ("vin_n", models.PositiveIntegerField()),
                ("vin_previous_txid", doge_indexer.models.model_utils.HexString32ByteField(max_length=64)),
                ("vin_vout_index", models.PositiveIntegerField()),
                ("vin_sequence", models.PositiveBigIntegerField()),
                ("vin_script_sig_asm", models.CharField()),
                ("vin_script_sig_hex", models.CharField()),
                (
                    "transaction_link",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="doge_indexer.dogetransaction"),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="dogetransaction",
            index=models.Index(fields=["block_number"], name="doge_indexe_block_n_a40f6a_idx"),
        ),
        migrations.AddIndex(
            model_name="dogetransaction",
            index=models.Index(fields=["timestamp"], name="doge_indexe_timesta_1f5a82_idx"),
        ),
        migrations.AddIndex(
            model_name="dogetransaction",
            index=models.Index(fields=["payment_reference"], name="doge_indexe_payment_bbf108_idx"),
        ),
        migrations.AddIndex(
            model_name="dogetransaction",
            index=models.Index(fields=["transaction_type"], name="doge_indexe_transac_ab078f_idx"),
        ),
        migrations.AddIndex(
            model_name="dogeblock",
            index=models.Index(fields=["block_number"], name="doge_indexe_block_n_afc447_idx"),
        ),
        migrations.AddIndex(
            model_name="dogeblock",
            index=models.Index(fields=["timestamp"], name="doge_indexe_timesta_752a6d_idx"),
        ),
        migrations.AddIndex(
            model_name="dogeblock",
            index=models.Index(fields=["previous_block_hash"], name="doge_indexe_previou_65de5f_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="transactionoutput",
            unique_together={("transaction_link", "n")},
        ),
        migrations.AlterUniqueTogether(
            name="transactioninput",
            unique_together={("transaction_link", "vin_n")},
        ),
    ]
